dj_startbootstrap/app_core_user/urls.py
# ----------------------------------------------------------------------------
# ../app_core_user/urls.py
# ----------------------------------------------------------------------------

from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'app_core_user'

urlpatterns = [
    # path('', views.index, name='index'),
    path('index.html', views.index, name='index'),
    path('index_02.html', views.index_02, name='index_02'),
    path('index_03_user.html', views.index_03_user, name='index_03_user'),
    path('index_04_userid.html', views.index_04_userid, name='index_04_userid'),
    path('index_05_user2userid.html', views.index_05_user2userid, name='index_05_user2userid'),
    path('index_06/<int:user_id>/', views.index_06_user, name='index_06_user'),
    path('index_13_user_new/', views.index_13_user_new, name='index_13_user_new'),
    path('index_14_userid_new/', views.index_14_userid_new, name='index_14_userid_new'),
    #
    #
    path("favicon.ico", RedirectView.as_view(
        url=staticfiles_storage.url("favicon.ico"))),
]

# ----------------------------------------------------------------------------
# http://127.0.0.1:8000/user/index.html
# http://127.0.0.1:8000/user/index_02.html
# http://127.0.0.1:8000/user/index_03_user.html
# http://127.0.0.1:8000/user/index_04_userid.html
# http://127.0.0.1:8000/user/index_05_user2userid.html
# http://127.0.0.1:8000/user/index_06/1/
# http://127.0.0.1:8000/user/index_13_user_new/
# http://127.0.0.1:8000/user/index_14_userid_new/
# ----------------------------------------------------------------------------

dj_startbootstrap/app_users/urls.py
# ../app_users/urls.py

from django.urls import path, include

from . import views

app_name = 'app_users'

urlpatterns = [
    # Schließt Standard-Authentifizierungs-URLs ein.
    path('', include('django.contrib.auth.urls')),
    #
    # Registrierungsseite.
    path('register/', views.register, name='register'),
]

# !!!
# mkdir ../templates/registration
# ../templates/registration/login.html
# ../templates/registration/logou.html
# . . .

dj_startbootstrap/core/urls.py
# ../core/urls.py

from django.contrib import admin
from django.urls import path, include
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('app_users.urls')),
    path('server/', include('app_core_server.urls')),
    path('user/', include('app_core_user.urls')),
    path('', include('app_web.urls')),
    # path('', include('app_web.urls')),
    # path('', include('app_core_server.urls')),
    # path('', include('app_core_user.urls')),
]

dj_startbootstrap/app_core_user/models.py
# ../app_core_user/models.py

from django.db import models


# ----------------------------------------------------------------------------
class User(models.Model):
    # id = int
    nname = models.CharField(max_length=32, null=False)
    vname = models.CharField(max_length=32, null=False)
    geb = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=64, null=True, blank=True, unique=True)
    is_active = models.BooleanField(null=False, default=True)
    date_beg = models.DateField(null=False, default='2000-01-01')
    date_end = models.DateField(null=False, default='2099-12-31')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "User"
        ordering = ["id", "nname", "vname"]

    def __str__(self):
        return f"{self.id}, {self.nname}, {self.vname}"


# ----------------------------------------------------------------------------
class UserId(models.Model):
    # id = int
    uid = models.CharField(max_length=32, null=False)
    is_active = models.BooleanField(null=False, default=True)
    date_beg = models.DateField(null=False, default='2000-01-01')
    date_end = models.DateField(null=False, default='2099-12-31')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "UserId"
        verbose_name_plural = "UserId"
        ordering = ["id", "uid"]

    def __str__(self):
        return f"{self.id}, {self.uid}"


# ----------------------------------------------------------------------------
class Z_user2userid(models.Model):
    t2t_user = models.ForeignKey(
        User,   verbose_name="User",   null=True, blank=False, on_delete=models.CASCADE)
    t2t_userid = models.ForeignKey(
        UserId, verbose_name="UserId", null=True, blank=False, on_delete=models.CASCADE)
    is_active = models.BooleanField(null=False, default=True)
    date_beg = models.DateField(null=False, default='2001-01-01')
    date_end = models.DateField(null=False, default='2099-12-31')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Z_user2userid"
        verbose_name_plural = "Z_user2userid"
        ordering = ["id", "t2t_user", "t2t_userid"]

    def __str__(self):
        return f"{self.id}, {self.t2t_user}, {self.t2t_userid}"

# id, t2t_user.id, t2t_user.nname, t2t_user.vname, t2t_userid.id, t2t_userid.uid

# # ----------------------------------------------------------------------------
# # open: 26.04.2021
# #
# # t2t: mitarbeiter - rolle - verfahren - komponente - remedy
#
# class Zt2t_ma2ro2ve2ko2re(models.Model):
#     t2t_mitarbeiter = models.ForeignKey(Mitarbeiter, verbose_name="Mitarbeiter", null=True, blank=False, on_delete=models.PROTECT)
#     t2t_rolle       = models.ForeignKey(Rolle, verbose_name="Rolle",             null=True, blank=False, on_delete=models.PROTECT)
#     t2t_verfahren   = models.ForeignKey(Verfahren, verbose_name="Verfahren",     null=True, blank=True,  on_delete=models.PROTECT)
#     t2t_komponente  = models.ForeignKey(Komponente, verbose_name="Komponente",   null=True, blank=True,  on_delete=models.PROTECT)
#     t2t_remedy      = models.ForeignKey(Remedy, verbose_name="Remedy",           null=True, blank=True,  on_delete=models.PROTECT)
#     check = models.BooleanField(null=False, default=False)
#     is_active = models.BooleanField(null=False, default=True)
#     date_beg = models.DateField(null=False)
#     date_end = models.DateField(null=False, default='2099-12-31')
#     date_created = models.DateTimeField(auto_now_add=True)
#     date_modified = models.DateTimeField(auto_now=True)
#
#     class Meta:
#         verbose_name = "Zt2t_ma2ro2ve2ko2re"
#         verbose_name_plural = "Zt2t_ma2ro2ve2ko2re"
#         ordering = ["t2t_mitarbeiter"]
#
#     def __str__(self):
#         return f"{self.t2t_mitarbeiter}"
#         #return f"{self.t2t_mitarbeiter}, {self.t2t_rolle}"
#         #return f"{self.t2t_mitarbeiter}, {self.t2t_rolle}, {self.t2t_verfahren}, {self.t2t_komponente}, {self.t2t_remedy}"

dj_startbootstrap/app_core_user/forms.py
# -----------------------------------------------------------
# ../app_core_user/forms.py

from django import forms
from .models import User, UserId, Z_user2userid


class UserForm(forms.ModelForm):
    class Meta:
        model = User

        fields = ['nname', 'vname', 'geb', 'email',
                  'is_active', 'date_beg', 'date_end']

        labels = {
            'nname': 'nname',
            'vname': 'vname',
            'geb': 'geb (yyyy-mm-dd)',
            'email': 'email',
            'is_active': 'is_active',
            'date_beg': 'date_beg (yyyy-mm-dd)',
            'date_end': 'date_end (yyyy-mm-dd)'
        }


class UserIdForm(forms.ModelForm):
    class Meta:
        model = UserId

        fields = ['uid', 'is_active', 'date_beg', 'date_end']

        labels = {
            'uid': 'uid',
            'is_active': 'is_active',
            'date_beg': 'date_beg (yyyy-mm-dd)',
            'date_end': 'date_end (yyyy-mm-dd)'
        }


class Z_user2useridForm(forms.ModelForm):
    class Meta:
        model = Z_user2userid

        fields = ['is_active', 'date_beg', 'date_end' ]

        labels = {
            'is_active': 'is_active',
            'date_beg': 'date_beg (yyyy-mm-dd)',
            'date_end': 'date_end (yyyy-mm-dd)'
        }
# https://stackoverflow.com/questions/5708650/how-do-i-add-a-foreign-key-field-to-a-modelform-in-django
# https://stackoverflow.com/questions/65218232/django-form-calling-foreign-key-field-attributes-in-template
# https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/
# https://qastack.com.de/programming/291945/how-do-i-filter-foreignkey-choices-in-a-django-modelform

#'id',
# 't2t_user.id', 't2t_user.nname', 't2t_user.vname', 't2t_user.geb', 't2t_user.email',
# 't2t_user.is_active', 't2t_user.date_beg', 't2t_user.date_end',
   
       
# id,
# t2t_user.id, t2t_user.nname, t2t_user.vname, t2t_user.geb, t2t_user.email,
# t2t_user.is_active, t2t_user.date_beg, t2t_user.date_end
#
# t2t_userid.id, t2t_userid.uid, t2t_userid.is_active, t2t_userid.date_beg, t2t_userid.date_end
# is_active, date_beg, date_end


# tipps: widgets = {'text': forms.Textarea(attrs={'cols': 80})}

dj_startbootstrap/app_core_user/views.py
# ../app_core_user/views.py

from django.shortcuts import render, redirect

from .models import User, UserId, Z_user2userid
from .forms import UserForm, UserIdForm


def index(request):
    """hp: index.html  -  stat."""
    return render(request, 'app_core_user/index.html')


def index_02(request):
    """hp: index_02.html  - stat. + base.html"""
    return render(request, 'app_core_user/index_02.html')


def index_03_user(request):
    """hp: index_03_user.html  -  abfrage: alle user"""
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'app_core_user/index_03_user.html', context)


def index_04_userid(request):
    """hp: index_04_userid.html  -  abfrage: alle userids"""
    userids = UserId.objects.order_by('uid')
    context = {'userids': userids}
    return render(request, 'app_core_user/index_04_userid.html', context)


def index_05_user2userid(request):
    """hp: index_05_user2userid.html  -  abfrage: """
    users = Z_user2userid.objects.order_by('id')
    context = {'users': users}
    return render(request, 'app_core_user/index_05_user2userid.html', context)


def index_06_user(request, user_id):
    """hp: index_06/<int:user_id>  -  abfrage: einzelne user durch die user_id"""
    userid = User.objects.get(id=user_id)
    userids = userid.z_user2userid_set.all()
    #userids = userid.z_user2userid_set.order_by('-date_added')
    context = {'userid': userid, 'userids': userids}
    return render(request, 'app_core_user/index_06_user.html', context)


def index_13_user_new(request):
    """ Add a new user  -  http://127.0.0.1:8000/user/index_13_user_new/ """
    if request.method != 'POST':
        # Keine Daten übermittelt; es wird ein leeres Formular erstellt
        form = UserForm()
    else:
        # POST-Daten übermittelt; Daten werden verarbeitet
        form = UserForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_core_user:index_03_user')

    # Zeigt ein leeres oder ein als ungültiges erkanntes Formular an
    context = {'form': form}
    return render(request, 'app_core_user/index_13_user_new.html', context)


def index_14_userid_new(request):
    """Add a new userid"""
    if request.method != 'POST':
        # Keine Daten übermittelt; es wird ein leeres Formular erstellt
        form = UserIdForm()
    else:
        # POST-Daten übermittelt; Daten werden verarbeitet
        form = UserIdForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_core_user:index_04_userid')

    # Zeigt ein leeres oder ein als ungültiges erkanntes Formular an.
    context = {'form': form}
    return render(request, 'app_core_user/index_14_userid_new.html', context)


# def index_15_user2userid_new(request):
#    """hp: index_05_user2userid.html  -  abfrage: """
#   users = Z_user2userid.objects.order_by('id')
#   context = {'users': users}
#   return render(request, 'app_core_user/index_05_user2userid.html', context)


# ============================================================================
# ../app_core_user/models.py
# ============================================================================
# ----------------------------------------------------------------------------
# class User(models.Model):
#     # id = int
#     nname = models.CharField(max_length=32, null=False)
#     vname = models.CharField(max_length=32, null=False)
#     geb = models.DateField(null=True, blank=True)
#     email = models.EmailField(max_length=64, null=True, blank=True, unique=True)
#     is_active = models.BooleanField(null=False, default=True)
#     date_beg = models.DateField(null=False, default='2000-01-01')
#     date_end = models.DateField(null=False, default='2099-12-31')
#     date_created = models.DateTimeField(auto_now_add=True)
#     date_modified = models.DateTimeField(auto_now=True)
# ----------------------------------------------------------------------------
# class UserId(models.Model):
#     # id = int
#     uid = models.CharField(max_length=32, null=False)
#     is_active = models.BooleanField(null=False, default=True)
#     date_beg = models.DateField(null=False, default='2000-01-01')
#     date_end = models.DateField(null=False, default='2099-12-31')
#     date_created = models.DateTimeField(auto_now_add=True)
#     date_modified = models.DateTimeField(auto_now=True)
# ----------------------------------------------------------------------------
# class Z_user2userid(models.Model):
#     t2t_user = models.ForeignKey(User, verbose_name="User", null=True, blank=False, on_delete=models.CASCADE)
#     t2t_userid = models.ForeignKey(UserId, verbose_name="UserId", null=True, blank=False, on_delete=models.CASCADE)
#     is_active = models.BooleanField(null=False, default=True)
#     date_beg = models.DateField(null=False, default='2001-01-01')
#     date_end = models.DateField(null=False, default='2099-12-31')
#     date_created = models.DateTimeField(auto_now_add=True)
#     date_modified = models.DateTimeField(auto_now=True)

# ============================================================================
# ../app_core_user/
# ============================================================================
# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------


# ----------------------------------------------------------------------------
# http://127.0.0.1:8000/user/index.html
# http://127.0.0.1:8000/user/index_02.html
# http://127.0.0.1:8000/user/index_03_user.html
# http://127.0.0.1:8000/user/index_04_userid.html
# http://127.0.0.1:8000/user/index_05_user2userid.html
# http://127.0.0.1:8000/user/index_06/1/
# http://127.0.0.1:8000/user/index_13_user_new/
# http://127.0.0.1:8000/user/index_14_userid_new/
# ----------------------------------------------------------------------------

dj_startbootstrap/templates/app_core_user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>title: app_core_user</title>
    <link rel="icon"href="{% static 'favicon.ico' %}">
</head>

<p>
    <a href="{% url 'app_core_user:index' %}">index</a> - 
    <a href="{% url 'app_core_user:index_02' %}">index_02</a> - 
    <a href="{% url 'app_core_user:index_03_user' %}">index_03_user</a> - 
    <a href="{% url 'app_core_user:index_04_userid' %}">index_04_userid</a> - 
    <a href="{% url 'app_core_user:index_05_user2userid' %}">index_05_user2userid</a> - 
    <a href="http://127.0.0.1:8000/user/index_06/1/">index_06_user</a> - 
    <a href="http://127.0.0.1:8000/user/index_13_user_new/">index_13_user_new</a> - 
    <a href="http://127.0.0.1:8000/user/index_14_userid_new/">index_14_userid_new</a> - 

    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'app_users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'app_users:register' %}">Register</a> -
        <a href="{% url 'app_users:login' %}">Log in</a>
    {% endif %}
</p>

<body>

{% block content %}
{% endblock content %}

</body>
</html>

dj_startbootstrap/templates/app_core_user/index.html
{% load static %}

<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>title: app_core_user__index.html</title>
    <link rel="icon"href="{% static 'favicon.ico' %}">
</head>
<body>
    <h1>body: app_core_user: index.html</h1>
</body>
</html>

dj_startbootstrap/templates/app_core_user/index_02.html
{% extends "app_core_user/base.html" %}

{% block content %}
    <p>app_core_user: index_02.html - extends base.html</p>
{% endblock content %}

dj_startbootstrap/templates/app_core_user/index_03_user.html
{% extends "app_core_user/base.html" %}

{% block content %}

<ul>
{% for user in users %}
    <li>{{ user }}</li>
{% empty %}
    <li>keine Eintraege vorhanden</li>
{% endfor %}
</ul>


<ul>
    {% for user in users %}
        <li>
        <a href="{% url 'app_core_user:index_06_user' user.id %}">{{ user.nname }}, {{ user.vname }}</a>
        </li>
    {% empty %}
        <li>keine Eintraege vorhanden</li>
    {% endfor %}
    </ul>


<br>

    <style>
        table, th, td {
        border: 1px solid black;
        }

    </style>
    <table>
        <tr>
          <th>user.id</th>
          <th>user.nname</th>
          <th>user.vname</th>
          <th>user.geb</th>
          <th>user.mail</th>
          <th>user.is_active</th>
          <th>user.date_beg</th>
          <th>user.date_end</th>
          <th>user.date_created</th>
          <th>user.date_modified</th>
        </tr>
        {% for user in users %}
        <tr>
            <td> {{ user.id }} </td>
            <td> <a href="{% url 'app_core_user:index_06_user' user.id %}"> {{ user.nname }} </a></td>
            <td> {{ user.vname }} </td>
            <td> {{ user.geb }} </td>
            <td> {{ user.mail }} </td>
            <td> {{ user.is_active }} </td>
            <td> {{ user.date_beg }} </td>
            <td> {{ user.date_end }} </td>
            <td> {{ user.date_created }} </td>
            <td> {{ user.date_modified }} </td>
        </tr>
        {% empty %}
            <li>keine Eintraege vorhanden</li>
        {% endfor %}
    </table> 

{% endblock content %}

dj_startbootstrap/templates/app_core_user/index_04_userid.html
{% extends "app_core_user/base.html" %}

{% block content %}

<ul>
{% for userid in userids %}
    <li>{{ userid }}</li>
{% empty %}
    <li>keine Eintraege vorhanden</li>
{% endfor %}
</ul>

<br>

    <style>
        table, th, td {
        border: 1px solid black;
        }
    </style>
    <table>
        <tr>
          <th>userid.id</th>
          <th>userid.uid</th>
          <th>userid.is_active</th>
          <th>userid.date_beg</th>
          <th>userid.date_end</th>
          <th>userid.date_created</th>
          <th>userid.date_modified</th>
        </tr>
        {% for userid in userids %}
        <tr>
            <td> {{ userid.id }} </td>
            <td> {{ userid.uid }} </td>
            <td> {{ userid.is_active }} </td>
            <td> {{ userid.date_beg }} </td>
            <td> {{ userid.date_end }} </td>
            <td> {{ userid.date_created }} </td>
            <td> {{ userid.date_modified }} </td>
        </tr>
        {% empty %}
            <li>keine Eintraege vorhanden</li>
        {% endfor %}
    </table> 

{% endblock content %}

dj_startbootstrap/templates/app_core_user/index_05_user2userid.html
{% extends "app_core_user/base.html" %}

{% block content %}

<ul>
{% for user in users %}
    <li>{{ user }}</li>
{% empty %}
    <li>keine Eintraege vorhanden</li>
{% endfor %}
</ul>

<br>

    <style>
        table, th, td {
        border: 1px solid black;
        }
    </style>
    <table>
        <tr>
          <th>id</th>
          <th>user.id</th>
          <th>user.nname</th>
          <th>user.vname</th>
          <th>userid.id</th>
          <th>userid.uid</th>
        </tr>
        {% for user in users %}
        <tr>
            <td> {{ user.id }} </td>
            <td> {{ user.t2t_user.id }} </td>
            <td> {{ user.t2t_user.nname }} </td>
            <td> {{ user.t2t_user.vname }} </td>
            <td> {{ user.t2t_userid.id }} </td>
            <td> {{ user.t2t_userid.uid }} </td>
        </tr>
        {% empty %}
            <li>keine Eintraege vorhanden</li>
        {% endfor %}
    </table> 

{% endblock content %}

dj_startbootstrap/templates/app_core_user/index_06_user.html
{% extends "app_core_user/base.html" %}

{% block content %}

<!-- context = {'userid': userid, 'userids': userids} -->
<!-- http://127.0.0.1:8000/user/index_06/1/ -->

<p>Userid: {{ userid }}</p>
<p>userids:</p>
<ul>
    {% for i in userids %}
    <li>
        {{ i }}
        {{ i.t2t_user }}
        {{ i.t2t_user.id }}
        {{ i.t2t_user.nname }}
        {{ i.t2t_user.vname }}
        {{ i.t2t_userid }}
        {{ i.t2t_userid.id }}
        {{ i.t2t_userid.uid }}
        {{ i | linebreaks }}
        <hr>
    </li>
    {% empty %}
        <li>keine Eintraege vorhanden ({{ userid }})</li>
    {% endfor %}
</ul>

<br>

    <style>
        table, th, td {
        border: 1px solid black;
        }
    </style>
    <table>
        <tr>
          <th>i</th>
          <th>i.t2t_user</th>
          <th>i.t2t_user.id</th>
          <th>i.t2t_user.nname</th>
          <th>i.t2t_user.vname</th>
          <th>i.t2t_userid</th>
          <th>i.t2t_userid.id</th>
          <th>i.t2t_userid.uid</th>
        </tr>
        {% for i in userids %}
        <tr>
            <td> {{ i }} </td>
            <td> {{ i.t2t_user }} </td>
            <td> {{ i.t2t_user.id }} </td>
            <td> {{ i.t2t_user.nname }} </td>
            <td> {{ i.t2t_user.vname }} </td>
            <td> {{ i.t2t_userid }} </td>
            <td> {{ i.t2t_userid.id }} </td>
            <td> {{ i.t2t_userid.uid }} </td>
        </tr>
        {% empty %}
            <li>keine Eintraege vorhanden</li>
        {% endfor %}
    </table> 

{% endblock content %}

dj_startbootstrap/templates/app_core_user/index_13_user_new.html
{% extends "app_core_user/base.html" %}

{% block content %}

<p>Add a new User:</p>
<form action="{% url 'app_core_user:index_13_user_new' %}" method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button name="submit">Add User</button>
</form>

{% endblock content %}

dj_startbootstrap/templates/app_core_user/index_14_userid_new.html
{% extends "app_core_user/base.html" %}

{% block content %}

<p>Add a new UserId:</p>
<form action="{% url 'app_core_user:index_14_userid_new' %}" method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button name="submit">Add UserId</button>
</form>

{% endblock content %}