py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/urls.py
# ../app_learnings_logs/urls.py

from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]


"""
urlpatterns:
1. Argument von path:   ''      ->      http://127.0.0.1:8000/
2. Argument von path:   gibt an, welche Funktion in views.py
aufgerufen werden soll -> index() in views.py
3. Argument von path:   gibt diesem URL-Muster den Namen index, sodass wir in anderen Codeabschnitten darauf verweisen können
"""

py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/models.py
# ../app_learnings_logs/models.py

from django.db import models

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic  = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text   = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(f"{self.text}") > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/views.py
# ../app_learnings_logs/views.py

from django.shortcuts import render
from .models import Topic


def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> - 
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}
{% endblock content %}

py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'Y-m-d - H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <hr>
    </li>
    {% empty %}
    <li>There are no entries for this topic ({{ topic }}) yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

py__ebook__crashkurs__dj-app/dj_kap-18_fertig/apps__learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <!-- <li>{{ topic }}</li>   # 1. versuch -->
            <li>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}